spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/portfolio
    username: moneytrackeruser
    password: securepassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.ws.client: DEBUG
    org.springframework.ws.server: DEBUG